branches:
  only:
    - master
    - develop

matrix:
  include:
    - language: python
      python:
        - 3.8
      install:
        - pip install -r build/requirements/requirements_dev.txt
      script:
        - black --check --verbose .
        - flake8 --config build/linting/.flake8 .
        - coverage run --source=./eNMS -m pytest
      after_success:
        - coveralls

    - language: node_js
      node_js:
        - "node"
      script:
        - npm run prettier
        - # npm run lint
