language: python

python:
  - 3.6

install:
  - pip install coveralls
  - pip install -r requirements.txt

before_script:
  cd tests/

script:
  - coverage run --source=../source -m pytest

after_success:
  - coveralls
